import { useCallback, useEffect, useState } from 'react';
import { useForm, useWatch, type FieldErrors, type UseFormRegister } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowLeft, Loader2, Save, ShieldAlert } from 'lucide-react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import { useApp } from '../../hooks/useApp';
import { useAuth } from '../../hooks/useAuth';
import { hasPermission } from '../../lib/authPermissions';
import { getApiErrorMessage, localInputToUtc, utcToLocalInput } from '../../lib/marketingCampaignUtils';
import { marketingCampaignService } from '../../services/marketingCampaignService';
import { CAMPAIGN_TYPES, DISCOUNT_TYPES, MARKETING_CAMPAIGN_PERMISSION, TRIGGER_TYPES, type MarketingCampaignAdmin, type MarketingCampaignPayload, type MarketingCampaignTranslationInput } from '../../types/marketingCampaign';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Checkbox } from '../ui/checkbox';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Switch } from '../ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { Textarea } from '../ui/textarea';
import { MarketingCampaignAnalytics } from './MarketingCampaignAnalytics';
import { MarketingCampaignPreview } from './MarketingCampaignPreview';

const translationSchema = z.object({
  headline: z.string().trim().min(1).max(250), description: z.string().max(2000), emailPlaceholder: z.string().max(200),
  buttonText: z.string().trim().min(1).max(100), closeText: z.string().max(100), successTitle: z.string().trim().min(1).max(250),
  successMessage: z.string().trim().min(1).max(2000), successButtonText: z.string().max(100), termsText: z.string().max(2000),
});
const numericString = (min: number, max?: number) => z.string().refine((value) => value !== '' && Number.isFinite(Number(value)) && Number(value) >= min && (max == null || Number(value) <= max));
const optionalNumericString = (min: number, max?: number) => z.string().refine((value) => value === '' || (Number.isFinite(Number(value)) && Number(value) >= min && (max == null || Number(value) <= max)));
const formSchema = z.object({
  name: z.string().trim().min(1).max(150), campaignType: z.enum(CAMPAIGN_TYPES), isActive: z.boolean(), priority: numericString(-2147483648, 2147483647),
  discountType: z.enum(['NONE', ...DISCOUNT_TYPES]), discountValue: z.string(), discountCode: z.string().max(100), minimumOrderAmount: optionalNumericString(0, 1000000), newCustomersOnly: z.boolean(),
  targetAllPages: z.boolean(), targetPagePattern: z.string().max(500), desktopEnabled: z.boolean(), mobileEnabled: z.boolean(), triggerType: z.enum(TRIGGER_TYPES),
  triggerDelaySeconds: optionalNumericString(0, 86400), scrollPercentage: optionalNumericString(0, 100), exitIntentEnabled: z.boolean(), frequencyDays: numericString(0, 3650),
  startDateLocal: z.string(), endDateLocal: z.string(), translations: z.object({ en: translationSchema, ar: translationSchema }),
}).superRefine((value, context) => {
  if (!value.desktopEnabled && !value.mobileEnabled) context.addIssue({ code: 'custom', path: ['desktopEnabled'], message: 'At least one device must be enabled.' });
  if (!value.targetAllPages && (!value.targetPagePattern.trim() || (value.targetPagePattern !== '*' && !value.targetPagePattern.startsWith('/')) || value.targetPagePattern.includes('..'))) context.addIssue({ code: 'custom', path: ['targetPagePattern'], message: 'Enter * or a relative path glob beginning with /.' });
  if (value.discountType !== 'NONE') {
    const amount = Number(value.discountValue);
    if (!value.discountValue || !Number.isFinite(amount) || amount < 0.001 || amount > 1000000) context.addIssue({ code: 'custom', path: ['discountValue'], message: 'Enter a valid discount value.' });
    if (value.discountType === 'PERCENTAGE' && amount > 100) context.addIssue({ code: 'custom', path: ['discountValue'], message: 'Percentage cannot exceed 100.' });
  }
  if (value.triggerType === 'DELAY' && value.triggerDelaySeconds === '') context.addIssue({ code: 'custom', path: ['triggerDelaySeconds'], message: 'Delay is required.' });
  if (value.triggerType === 'SCROLL' && value.scrollPercentage === '') context.addIssue({ code: 'custom', path: ['scrollPercentage'], message: 'Scroll percentage is required.' });
  if (value.startDateLocal && value.endDateLocal && new Date(value.endDateLocal) <= new Date(value.startDateLocal)) context.addIssue({ code: 'custom', path: ['endDateLocal'], message: 'End must be after start.' });
});
type FormValues = z.infer<typeof formSchema>;

const emptyTranslation = () => ({ headline: '', description: '', emailPlaceholder: '', buttonText: '', closeText: '', successTitle: '', successMessage: '', successButtonText: '', termsText: '' });
const defaults: FormValues = { name: '', campaignType: 'NEWSLETTER', isActive: false, priority: '0', discountType: 'NONE', discountValue: '', discountCode: '', minimumOrderAmount: '', newCustomersOnly: false, targetAllPages: true, targetPagePattern: '', desktopEnabled: true, mobileEnabled: true, triggerType: 'DELAY', triggerDelaySeconds: '3', scrollPercentage: '50', exitIntentEnabled: false, frequencyDays: '0', startDateLocal: '', endDateLocal: '', translations: { en: emptyTranslation(), ar: emptyTranslation() } };
const clean = (value: string): string | null => value.trim() || null;
const toTranslation = (languageCode: 'en' | 'ar', value: FormValues['translations']['en']): MarketingCampaignTranslationInput => ({ languageCode, headline: value.headline.trim(), description: clean(value.description), emailPlaceholder: clean(value.emailPlaceholder), buttonText: value.buttonText.trim(), closeText: clean(value.closeText), successTitle: value.successTitle.trim(), successMessage: value.successMessage.trim(), successButtonText: clean(value.successButtonText), termsText: clean(value.termsText) });
const campaignToForm = (campaign: MarketingCampaignAdmin): FormValues => {
  const translation = (code: 'en' | 'ar') => { const item = campaign.translations.find((entry) => entry.languageCode === code); return item ? { headline: item.headline, description: item.description ?? '', emailPlaceholder: item.emailPlaceholder ?? '', buttonText: item.buttonText, closeText: item.closeText ?? '', successTitle: item.successTitle, successMessage: item.successMessage, successButtonText: item.successButtonText ?? '', termsText: item.termsText ?? '' } : emptyTranslation(); };
  return { name: campaign.name, campaignType: CAMPAIGN_TYPES.includes(campaign.campaignType as (typeof CAMPAIGN_TYPES)[number]) ? campaign.campaignType as FormValues['campaignType'] : 'NEWSLETTER', isActive: campaign.isActive, priority: String(campaign.priority), discountType: campaign.discountType && DISCOUNT_TYPES.includes(campaign.discountType as (typeof DISCOUNT_TYPES)[number]) ? campaign.discountType as FormValues['discountType'] : 'NONE', discountValue: campaign.discountValue?.toString() ?? '', discountCode: campaign.discountCode ?? '', minimumOrderAmount: campaign.minimumOrderAmount?.toString() ?? '', newCustomersOnly: campaign.newCustomersOnly, targetAllPages: campaign.targetAllPages, targetPagePattern: campaign.targetPagePattern ?? '', desktopEnabled: campaign.desktopEnabled, mobileEnabled: campaign.mobileEnabled, triggerType: TRIGGER_TYPES.includes(campaign.triggerType as (typeof TRIGGER_TYPES)[number]) ? campaign.triggerType as FormValues['triggerType'] : 'DELAY', triggerDelaySeconds: campaign.triggerDelaySeconds?.toString() ?? '', scrollPercentage: campaign.scrollPercentage?.toString() ?? '', exitIntentEnabled: campaign.exitIntentEnabled, frequencyDays: String(campaign.frequencyDays), startDateLocal: utcToLocalInput(campaign.startDateUtc), endDateLocal: utcToLocalInput(campaign.endDateUtc), translations: { en: translation('en'), ar: translation('ar') } };
};

function Field({ label, error, children, description }: { label: string; error?: string; children: React.ReactNode; description?: string }) { return <div className="space-y-2"><Label>{label}</Label>{children}{description && <p className="text-xs text-muted-foreground">{description}</p>}{error && <p className="text-xs text-destructive">{error}</p>}</div>; }
function TranslationFields({ code, register, errors }: { code: 'en' | 'ar'; register: UseFormRegister<FormValues>; errors?: FieldErrors<FormValues['translations']['en']> }) { const { t } = useApp(); const dir = code === 'ar' ? 'rtl' : 'ltr'; return <div dir={dir} className="grid gap-4 md:grid-cols-2"><Field label={t('admin.marketingCampaigns.headline')} error={errors?.headline?.message}><Input dir={dir} {...register(`translations.${code}.headline`)} /></Field><Field label={t('admin.marketingCampaigns.emailPlaceholder')} error={errors?.emailPlaceholder?.message}><Input dir={dir} {...register(`translations.${code}.emailPlaceholder`)} /></Field><div className="md:col-span-2"><Field label={t('admin.marketingCampaigns.contentDescription')} error={errors?.description?.message}><Textarea dir={dir} rows={3} {...register(`translations.${code}.description`)} /></Field></div><Field label={t('admin.marketingCampaigns.buttonText')} error={errors?.buttonText?.message}><Input dir={dir} {...register(`translations.${code}.buttonText`)} /></Field><Field label={t('admin.marketingCampaigns.closeText')} error={errors?.closeText?.message}><Input dir={dir} {...register(`translations.${code}.closeText`)} /></Field><Field label={t('admin.marketingCampaigns.successTitle')} error={errors?.successTitle?.message}><Input dir={dir} {...register(`translations.${code}.successTitle`)} /></Field><Field label={t('admin.marketingCampaigns.successButtonText')} error={errors?.successButtonText?.message}><Input dir={dir} {...register(`translations.${code}.successButtonText`)} /></Field><div className="md:col-span-2"><Field label={t('admin.marketingCampaigns.successMessage')} error={errors?.successMessage?.message}><Textarea dir={dir} rows={3} {...register(`translations.${code}.successMessage`)} /></Field></div><div className="md:col-span-2"><Field label={t('admin.marketingCampaigns.termsText')} error={errors?.termsText?.message}><Textarea dir={dir} rows={3} {...register(`translations.${code}.termsText`)} /></Field></div></div>; }

export function MarketingCampaignEditor() {
  const { campaignId } = useParams(); const id = campaignId ? Number(campaignId) : null; const editing = Number.isInteger(id);
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const { t } = useApp(); const { user } = useAuth();
  const authorized = hasPermission(MARKETING_CAMPAIGN_PERMISSION, user?.roles); const [loading, setLoading] = useState(editing); const [loadError, setLoadError] = useState(''); const [archived, setArchived] = useState(false);
  const form = useForm<FormValues>({ resolver: zodResolver(formSchema), defaultValues: defaults });
  const { register, handleSubmit, reset, watch, setValue, control, formState: { errors, isSubmitting } } = form;
  const values = watch(); const initialTab = editing && searchParams.get('tab') === 'analytics' ? 'analytics' : 'general';
  const previewContent = useWatch({ control, name: 'translations' });
  const back = useCallback(() => navigate(editing ? '../..' : '..', { relative: 'path' }), [editing, navigate]);

  useEffect(() => { if (!editing || !id || !authorized) { setLoading(false); return; } let active = true; (async () => { try { const campaign = await marketingCampaignService.getById(id); if (active) { reset(campaignToForm(campaign)); setArchived(Boolean(campaign.archivedAt)); } } catch (error) { if (active) setLoadError(getApiErrorMessage(error, t('admin.marketingCampaigns.loadOneError'))); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [authorized, editing, id, reset, t]);

  const previewTranslations = {
    en: toTranslation('en', previewContent.en),
    ar: toTranslation('ar', previewContent.ar),
  };
  const onSubmit = async (data: FormValues) => {
    const discount = data.discountType === 'NONE' ? null : data.discountType;
    const payload: MarketingCampaignPayload = { name: data.name.trim(), campaignType: data.campaignType, isActive: data.isActive, priority: Number(data.priority), discountType: discount, discountValue: discount ? Number(data.discountValue) : null, discountCode: discount ? clean(data.discountCode) : null, minimumOrderAmount: discount && data.minimumOrderAmount ? Number(data.minimumOrderAmount) : null, newCustomersOnly: data.newCustomersOnly, targetAllPages: data.targetAllPages, targetPagePattern: data.targetAllPages ? null : clean(data.targetPagePattern), desktopEnabled: data.desktopEnabled, mobileEnabled: data.mobileEnabled, triggerType: data.triggerType, triggerDelaySeconds: data.triggerType === 'DELAY' ? Number(data.triggerDelaySeconds) : null, scrollPercentage: data.triggerType === 'SCROLL' ? Number(data.scrollPercentage) : null, exitIntentEnabled: data.exitIntentEnabled, frequencyDays: Number(data.frequencyDays), startDateUtc: localInputToUtc(data.startDateLocal), endDateUtc: localInputToUtc(data.endDateLocal), translations: [toTranslation('en', data.translations.en), toTranslation('ar', data.translations.ar)] };
    try { if (editing && id) await marketingCampaignService.update(id, payload); else await marketingCampaignService.create(payload); toast.success(t(editing ? 'admin.marketingCampaigns.updateSuccess' : 'admin.marketingCampaigns.createSuccess')); back(); } catch (error) { toast.error(getApiErrorMessage(error, t('admin.marketingCampaigns.saveError'))); }
  };

  if (!authorized) return <Alert variant="destructive"><ShieldAlert className="h-4 w-4" /><AlertTitle>{t('admin.marketingCampaigns.notAuthorized')}</AlertTitle><AlertDescription>{t('admin.marketingCampaigns.permissionRequired')}</AlertDescription></Alert>;
  if (loading) return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;
  if (loadError) return <Alert variant="destructive"><AlertTitle>{t('admin.marketingCampaigns.loadOneError')}</AlertTitle><AlertDescription>{loadError}</AlertDescription></Alert>;

  const translationError = errors.translations;
  return <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Button type="button" size="icon" variant="outline" onClick={back}><ArrowLeft className="h-4 w-4" /></Button><div><h1 className="text-2xl font-bold">{t(editing ? 'admin.marketingCampaigns.editCampaign' : 'admin.marketingCampaigns.newCampaign')}</h1><p className="text-sm text-muted-foreground">{t('admin.marketingCampaigns.editorDescription')}</p></div></div><Button type="submit" disabled={isSubmitting || archived}>{isSubmitting ? <Loader2 className="me-2 h-4 w-4 animate-spin" /> : <Save className="me-2 h-4 w-4" />}{t('admin.marketingCampaigns.save')}</Button></div>
    {archived && <Alert variant="destructive"><AlertTitle>{t('admin.marketingCampaigns.archivedReadOnly')}</AlertTitle></Alert>}
    <Tabs defaultValue={initialTab} className="space-y-4"><div className="overflow-x-auto pb-1"><TabsList className="inline-flex min-w-max">{['general','content','offer','targeting','display','schedule',...(editing ? ['analytics'] : [])].map((tab) => <TabsTrigger key={tab} value={tab}>{t(`admin.marketingCampaigns.tabs.${tab}`)}</TabsTrigger>)}</TabsList></div>
      <TabsContent value="general"><Card><CardHeader><CardTitle>{t('admin.marketingCampaigns.tabs.general')}</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label={t('admin.marketingCampaigns.name')} error={errors.name?.message}><Input {...register('name')} /></Field><Field label={t('admin.marketingCampaigns.type')}><Select value={values.campaignType} onValueChange={(value: FormValues['campaignType']) => setValue('campaignType', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{CAMPAIGN_TYPES.map((value) => <SelectItem key={value} value={value}>{t(`admin.marketingCampaigns.types.${value}`)}</SelectItem>)}</SelectContent></Select></Field><Field label={t('admin.marketingCampaigns.priority')} error={errors.priority?.message}><Input type="number" {...register('priority')} /></Field><div className="flex items-center gap-3 pt-7"><Switch checked={values.isActive} onCheckedChange={(checked) => setValue('isActive', checked)} /><Label>{t('admin.marketingCampaigns.active')}</Label></div></CardContent></Card></TabsContent>
      <TabsContent value="content" className="space-y-4"><Tabs defaultValue="en"><TabsList><TabsTrigger value="en">English</TabsTrigger><TabsTrigger value="ar">العربية</TabsTrigger></TabsList><TabsContent value="en"><Card><CardHeader><CardTitle>English</CardTitle></CardHeader><CardContent><TranslationFields code="en" register={register} errors={translationError?.en} /></CardContent></Card><MarketingCampaignPreview translation={previewTranslations.en} language="en" /></TabsContent><TabsContent value="ar"><Card><CardHeader><CardTitle>العربية</CardTitle></CardHeader><CardContent><TranslationFields code="ar" register={register} errors={translationError?.ar} /></CardContent></Card><MarketingCampaignPreview translation={previewTranslations.ar} language="ar" /></TabsContent></Tabs></TabsContent>
      <TabsContent value="offer" className="space-y-4"><Alert><AlertTitle>{t('admin.marketingCampaigns.discountNoticeTitle')}</AlertTitle><AlertDescription>{t('admin.marketingCampaigns.discountNotice')}</AlertDescription></Alert><Card><CardContent className="grid gap-4 pt-6 md:grid-cols-2"><Field label={t('admin.marketingCampaigns.discountType')}><Select value={values.discountType} onValueChange={(value: FormValues['discountType']) => setValue('discountType', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="NONE">{t('admin.marketingCampaigns.none')}</SelectItem>{DISCOUNT_TYPES.map((value) => <SelectItem key={value} value={value}>{t(`admin.marketingCampaigns.discountTypes.${value}`)}</SelectItem>)}</SelectContent></Select></Field>{values.discountType !== 'NONE' && <><Field label={t('admin.marketingCampaigns.discountValue')} error={errors.discountValue?.message}><Input type="number" min="0.001" step="0.001" {...register('discountValue')} /></Field><Field label={t('admin.marketingCampaigns.discountCode')}><Input {...register('discountCode')} /></Field><Field label={t('admin.marketingCampaigns.minimumOrder')} error={errors.minimumOrderAmount?.message}><Input type="number" min="0" step="0.001" {...register('minimumOrderAmount')} /></Field></>}<label className="flex items-center gap-3 md:col-span-2"><Checkbox checked={values.newCustomersOnly} onCheckedChange={(checked) => setValue('newCustomersOnly', checked === true)} /><span className="text-sm font-medium">{t('admin.marketingCampaigns.newCustomersOnly')}</span></label></CardContent></Card></TabsContent>
      <TabsContent value="targeting"><Card><CardContent className="space-y-5 pt-6"><div className="flex items-center justify-between gap-4"><div><Label>{t('admin.marketingCampaigns.targetAllPages')}</Label><p className="text-xs text-muted-foreground">{t('admin.marketingCampaigns.targetAllPagesHelp')}</p></div><Switch checked={values.targetAllPages} onCheckedChange={(checked) => setValue('targetAllPages', checked)} /></div>{!values.targetAllPages && <Field label={t('admin.marketingCampaigns.targetPattern')} error={errors.targetPagePattern?.message} description={t('admin.marketingCampaigns.targetPatternHelp')}><Input placeholder="/om/products/*" {...register('targetPagePattern')} /><div className="flex flex-wrap gap-2">{['*','/om/shop','/om/products/*','/sa/shop','/sa/products/*'].map((example) => <Badge key={example} variant="outline">{example}</Badge>)}</div></Field>}</CardContent></Card></TabsContent>
      <TabsContent value="display"><Card><CardContent className="grid gap-5 pt-6 md:grid-cols-2"><label className="flex items-center gap-3"><Checkbox checked={values.desktopEnabled} onCheckedChange={(checked) => setValue('desktopEnabled', checked === true, { shouldValidate: true })} /><span>{t('admin.marketingCampaigns.desktopEnabled')}</span></label><label className="flex items-center gap-3"><Checkbox checked={values.mobileEnabled} onCheckedChange={(checked) => setValue('mobileEnabled', checked === true, { shouldValidate: true })} /><span>{t('admin.marketingCampaigns.mobileEnabled')}</span></label>{errors.desktopEnabled && <p className="text-xs text-destructive md:col-span-2">{errors.desktopEnabled.message}</p>}<Field label={t('admin.marketingCampaigns.triggerType')}><Select value={values.triggerType} onValueChange={(value: FormValues['triggerType']) => setValue('triggerType', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{TRIGGER_TYPES.map((value) => <SelectItem key={value} value={value}>{t(`admin.marketingCampaigns.triggerTypes.${value}`)}</SelectItem>)}</SelectContent></Select></Field>{values.triggerType === 'DELAY' ? <Field label={t('admin.marketingCampaigns.delaySeconds')} error={errors.triggerDelaySeconds?.message}><Input type="number" min="0" max="86400" {...register('triggerDelaySeconds')} /></Field> : <Field label={t('admin.marketingCampaigns.scrollPercentage')} error={errors.scrollPercentage?.message}><Input type="number" min="0" max="100" {...register('scrollPercentage')} /></Field>}<div className="flex items-start justify-between gap-4 md:col-span-2"><div><Label>{t('admin.marketingCampaigns.exitIntent')}</Label><p className="text-xs text-muted-foreground">{t('admin.marketingCampaigns.exitIntentHelp')}</p></div><Switch checked={values.exitIntentEnabled} onCheckedChange={(checked) => setValue('exitIntentEnabled', checked)} /></div><div className="md:col-span-2"><Field label={t('admin.marketingCampaigns.frequencyDays')} error={errors.frequencyDays?.message} description={t('admin.marketingCampaigns.frequencyHelp')}><Input type="number" min="0" max="3650" {...register('frequencyDays')} /></Field></div></CardContent></Card></TabsContent>
      <TabsContent value="schedule"><Card><CardHeader><CardTitle>{t('admin.marketingCampaigns.tabs.schedule')}</CardTitle><CardDescription>{t('admin.marketingCampaigns.scheduleHelp')}</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label={t('admin.marketingCampaigns.startDate')}><Input type="datetime-local" {...register('startDateLocal')} /></Field><Field label={t('admin.marketingCampaigns.endDate')} error={errors.endDateLocal?.message}><Input type="datetime-local" {...register('endDateLocal')} /></Field></CardContent></Card></TabsContent>
      {editing && id && <TabsContent value="analytics"><MarketingCampaignAnalytics campaignId={id} /></TabsContent>}
    </Tabs>
  </form>;
}
